# 文件路径: config/west.yml
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v3.5  # <--- [关键修正] 将版本固定到与构建环境匹配的 v3.5
      import: app/west.yml
  self:
    path: config