# 文件路径: config/west.yml
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main  # <--- [关键修正] 改回 'main'
      import: app/west.yml
  self:
    path: config