manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zzeneg
      url-base: https://github.com/zzeneg
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # 这是我们唯一需要添加的外部模块
    - name: zmk-raw-hid
      remote: zzeneg
      revision: main
  self:
    path: config
