name: 'Build ZMK Firmware'

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.5
    strategy:
      matrix:
        board: [nice_nano_v2]
        shield: [2percentmilk] # 我使用了你日志中提供的 shield 名称。
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Build (Pristine)
        run: west build -p -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }}

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.board }}-${{ matrix.shield }}
          path: zmk/app/build/zephyr/zmk.uf2
