name: 'Build ZMK Firmware'

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.5
      
    strategy:
      matrix:
        board: [nice_nano_v2]
        shield: [2percentmilk]
        
    steps:
      - name: Checkout user config
        uses: actions/checkout@v4
        with:
          path: zmk-config

      - name: Checkout ZMK
        uses: actions/checkout@v4
        with:
          repository: zmkfirmware/zmk
          path: zmk

      - name: Initialize West
        run: |
          cd zmk
          west init -l app --mf west-zmk.yml
          cd ..

      - name: Update West Dependencies
        run: |
          cd zmk
          west update
          cd ..

      - name: Build Firmware
        run: |
          cd zmk
          west build -p -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }} -DZMK_CONFIG="${{ github.workspace }}/zmk-config/config"
          cd ..
          
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.board }}-${{ matrix.shield }}
          path: zmk/app/build/zephyr/zmk.uf2
